// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterMonitoring.proto

package ds.waterMonitoring;

public interface AreaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterMonitoring.AreaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string areaName = 1;</code>
   */
  java.lang.String getAreaName();
  /**
   * <code>string areaName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaNameBytes();
}
