// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public interface LevelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecyclingService.LevelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tankId = 1;</code>
   */
  int getTankId();

  /**
   * <code>int32 currentLevel = 2;</code>
   */
  int getCurrentLevel();
}
