// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public interface RainwaterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterRecycling.RainwaterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentTankUsed = 2;</code>
   */
  int getCurrentTankUsed();
}
