// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public interface RainwaterTankOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterRecycling.RainwaterTank)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tankId = 1;</code>
   */
  int getTankId();

  /**
   * <code>int32 tankLevels = 2;</code>
   */
  int getTankLevels();
}
