// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterRecycling.proto

package ds.waterRecycling;

public final class WaterRecyclingImpl {
  private WaterRecyclingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_TankRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_TankRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_TankResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_TankResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_MonitorLevels_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_MonitorLevels_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_LevelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_LevelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_RainwaterTank_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_RainwaterTank_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterRecycling_RainwaterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterRecycling_RainwaterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024waterRecycling.proto\022\016waterRecycling\"\035" +
      "\n\013TankRequest\022\016\n\006tankId\030\001 \001(\005\"!\n\014TankRes" +
      "ponse\022\021\n\ttankLevel\030\001 \001(\005\"\037\n\rMonitorLevel" +
      "s\022\016\n\006tankId\030\001 \001(\005\"6\n\016LevelsResponse\022\016\n\006t" +
      "ankId\030\001 \001(\005\022\024\n\014currentLevel\030\002 \001(\005\"3\n\rRai" +
      "nwaterTank\022\016\n\006tankId\030\001 \001(\005\022\022\n\ntankLevels" +
      "\030\002 \001(\005\",\n\021RainwaterResponse\022\027\n\017currentTa" +
      "nkUsed\030\002 \001(\0052\226\002\n\016WaterRecycling\022M\n\016Check" +
      "TankLevel\022\033.waterRecycling.TankRequest\032\034" +
      ".waterRecycling.TankResponse\"\000\022V\n\021Monito" +
      "rTankLevels\022\035.waterRecycling.MonitorLeve" +
      "ls\032\036.waterRecycling.LevelsResponse\"\0000\001\022]" +
      "\n\025SwitchToRainwaterTank\022\035.waterRecycling" +
      ".RainwaterTank\032!.waterRecycling.Rainwate" +
      "rResponse\"\000(\001B)\n\021ds.waterRecyclingB\022Wate" +
      "rRecyclingImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waterRecycling_TankRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waterRecycling_TankRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_TankRequest_descriptor,
        new java.lang.String[] { "TankId", });
    internal_static_waterRecycling_TankResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_waterRecycling_TankResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_TankResponse_descriptor,
        new java.lang.String[] { "TankLevel", });
    internal_static_waterRecycling_MonitorLevels_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_waterRecycling_MonitorLevels_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_MonitorLevels_descriptor,
        new java.lang.String[] { "TankId", });
    internal_static_waterRecycling_LevelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_waterRecycling_LevelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_LevelsResponse_descriptor,
        new java.lang.String[] { "TankId", "CurrentLevel", });
    internal_static_waterRecycling_RainwaterTank_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_waterRecycling_RainwaterTank_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_RainwaterTank_descriptor,
        new java.lang.String[] { "TankId", "TankLevels", });
    internal_static_waterRecycling_RainwaterResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_waterRecycling_RainwaterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterRecycling_RainwaterResponse_descriptor,
        new java.lang.String[] { "CurrentTankUsed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
