// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWaters.proto

package ds.hotWater;

public interface desiredTankTempOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotWater.desiredTankTemp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 desiredTemp = 1;</code>
   */
  int getDesiredTemp();
}
