// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWaters.proto

package ds.hotWater;

public final class hotWaterImpl {
  private hotWaterImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_desiredTankTemp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_desiredTankTemp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_TankTempConfirm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_TankTempConfirm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_UsageDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_UsageDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotWater_UsageDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hotWater_UsageDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017hotWaters.proto\022\010hotWater\"&\n\017desiredTa" +
      "nkTemp\022\023\n\013desiredTemp\030\001 \001(\005\"@\n\017TankTempC" +
      "onfirm\022\027\n\017currentTankTemp\030\001 \001(\005\022\024\n\014confi" +
      "rmation\030\002 \001(\t\"d\n\020UsageDataRequest\022\024\n\014hot" +
      "WaterTemp\030\001 \001(\005\022\021\n\ttankLevel\030\002 \001(\005\022\020\n\010fl" +
      "owRate\030\003 \001(\005\022\025\n\rwaterPressure\030\004 \001(\005\"+\n\021U" +
      "sageDataResponse\022\026\n\016recommendation\030\001 \001(\t" +
      "2\255\001\n\017HotWaterService\022L\n\022SetTankTemperatu" +
      "re\022\031.hotWater.desiredTankTemp\032\031.hotWater" +
      ".TankTempConfirm\"\000\022L\n\rSendUsageData\022\032.ho" +
      "tWater.UsageDataRequest\032\033.hotWater.Usage" +
      "DataResponse\"\000(\001B\035\n\013ds.hotWaterB\014hotWate" +
      "rImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hotWater_desiredTankTemp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hotWater_desiredTankTemp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_desiredTankTemp_descriptor,
        new java.lang.String[] { "DesiredTemp", });
    internal_static_hotWater_TankTempConfirm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hotWater_TankTempConfirm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_TankTempConfirm_descriptor,
        new java.lang.String[] { "CurrentTankTemp", "Confirmation", });
    internal_static_hotWater_UsageDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hotWater_UsageDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_UsageDataRequest_descriptor,
        new java.lang.String[] { "HotWaterTemp", "TankLevel", "FlowRate", "WaterPressure", });
    internal_static_hotWater_UsageDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hotWater_UsageDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hotWater_UsageDataResponse_descriptor,
        new java.lang.String[] { "Recommendation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
