// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWaters.proto

package ds.hotWater;

public interface TankTempConfirmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotWater.TankTempConfirm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentTankTemp = 1;</code>
   */
  int getCurrentTankTemp();

  /**
   * <code>string confirmation = 2;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
