// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotWaters.proto

package ds.hotWater;

public interface UsageDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hotWater.UsageDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hotWaterTemp = 1;</code>
   */
  int getHotWaterTemp();

  /**
   * <code>int32 tankLevel = 2;</code>
   */
  int getTankLevel();

  /**
   * <code>int32 flowRate = 3;</code>
   */
  int getFlowRate();

  /**
   * <code>int32 waterPressure = 4;</code>
   */
  int getWaterPressure();
}
